language: python
python:
  - "2.7"

install:
  - pip install pipenv
  - pipenv install
script:
  - echo "no scripts"
after_success:
 - bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
 - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
